-- MySQL Script generated by MySQL Workbench
-- Thu Jan 16 20:14:19 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bankautomat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bankautomat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bankautomat` DEFAULT CHARACTER SET utf8mb4 ;
USE `bankautomat` ;

-- -----------------------------------------------------
-- Table `bankautomat`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bankautomat`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NULL,
  `lname` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankautomat`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bankautomat`.`account` (
  `idaccount` INT NOT NULL AUTO_INCREMENT,
  `balance` DECIMAL(15,2) NULL,
  `type_credit` TINYINT NULL,
  `credit_limit` DECIMAL(7,0) NULL,
  `iduser` INT NULL,
  PRIMARY KEY (`idaccount`),
  INDEX `iduser_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `iduser`
    FOREIGN KEY (`iduser`)
    REFERENCES `bankautomat`.`user` (`iduser`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankautomat`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bankautomat`.`card` (
  `idcard` INT NOT NULL AUTO_INCREMENT,
  `cardnum` VARCHAR(45) NULL,
  `pin` VARCHAR(255) NULL,
  `attempts` INT,
  `locked` TINYINT,
  `idaccount` INT NULL,
  UNIQUE (`cardnum`),
  PRIMARY KEY (`idcard`),
  INDEX `idaccount_idx` (`idaccount` ASC) VISIBLE,
  CONSTRAINT `idaccount_in_card`
    FOREIGN KEY (`idaccount`)
    REFERENCES `bankautomat`.`account` (`idaccount`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankautomat`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bankautomat`.`transaction` (
  `idtransaction` INT NOT NULL AUTO_INCREMENT,
  `time` DATETIME NULL,
  `amount` DECIMAL(15,2) NULL,
  `idaccount` INT NULL,
  PRIMARY KEY (`idtransaction`),
  INDEX `idaccount_idx` (`idaccount` ASC) VISIBLE,
  CONSTRAINT `idaccount_in_transaction`
    FOREIGN KEY (`idaccount`)
    REFERENCES `bankautomat`.`account` (`idaccount`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
